--name Spark_Website_Testing
--exclude donotrun
--exclude firefox
--exclude edge
--xunit Spark.xml
--listener time_logger.py
--outputdir reports
--output Spark-xml
--log Spark-log
--report Spark-report
--variable browser:chromium
--variable configuration:user01
--variable required_device:iPhone 13
--loglevel TRACE
--variable headless:false
--debugfile debug_gc.log
Robot_Tests/
